const players = [
  {
    id: 1,
    firstName: "Jean",
    lastName: "Tourloupe",
    emailPlayer: "sfbsdfbfsd",
    Password: "fva-1-Tourloupe",
    Man: true,
    joueur_interclubs: "equipe_1",
    joueur_capitaine: "capitaine_eq_1",
    droits: "capitaine",
    jour_ouverture: null,
    photos: "Jean_Tourloupe.jpg"
  },
  {
    id: 2,
    firstName: "Luc",
    lastName: "Harne",
    emailPlayer: "",
    Password: "fva-2-Harne",
    Man: true,
    joueur_interclubs: "equipe_2",
    joueur_capitaine: null,
    droits: "joueur",
    jour_ouverture: null,
    photos: "Luc _Harne.jpg"
  },
  {
    id: 3,
    firstName: "Olivier",
    lastName: "Tnam",
    emailPlayer: "",
    Password: "fva-3-Tnam",
    Man: true,
    joueur_interclubs: "loisir",
    joueur_capitaine: null,
    droits: "joueur",
    jour_ouverture: "lundi",
    photos: "Olivier _Tnam.jpg"
  },
  {
    id: 4,
    firstName: "Rémy",
    lastName: "Neur",
    emailPlayer: "",
    Password: "fva-4-Neur",
    Man: true,
    joueur_interclubs: "equipe_2",
    joueur_capitaine: null,
    droits: "joueur",
    jour_ouverture: null,
    photos: "Remy _Neur.jpg"
  },
  {
    id: 5,
    firstName: "Mélusine",
    lastName: "Engraiv",
    emailPlayer: "",
    Password: "fva-5-Engraiv",
    Man: false,
    joueur_interclubs: "equipe_2",
    joueur_capitaine: null,
    droits: "joueur",
    jour_ouverture: null,
    photos: "Melusine_Engraiv.jpg"
  },
  {
    id: 6,
    firstName: "Al",
    lastName: "Anbiqué",
    emailPlayer: "",
    Password: "fva-6-Anbique",
    Man: true,
    joueur_interclubs: "loisir",
    joueur_capitaine: null,
    droits: "joueur",
    jour_ouverture: null,
    photos: "Al_Anbique.jpg"
  },
  {
    id: 7,
    firstName: "Sam",
    lastName: "Soule",
    emailPlayer: "",
    Password: "fva-7-Soule",
    Man: true,
    joueur_interclubs: "loisir",
    joueur_capitaine: null,
    droits: "joueur",
    jour_ouverture: "mardi",
    photos: "Sam_Soule.jpg"
  },
  {
    id: 8,
    firstName: "Tara",
    lastName: "Clure",
    emailPlayer: "",
    Password: "fva-8-Clure",
    Man: false,
    joueur_interclubs: "equipe_1",
    joueur_capitaine: null,
    droits: "joueur",
    jour_ouverture: null,
    photos: "Tara_Clure.jpg"
  },
  {
    id: 9,
    firstName: "Gérard",
    lastName: "Manvussa",
    emailPlayer: "",
    Password: "fva-9-Manvussa",
    Man: true,
    joueur_interclubs: "equipe_2",
    joueur_capitaine: null,
    droits: "admin",
    jour_ouverture: null,
    photos: "Gerard_Manvussa.jpg"
  },
  {
    id: 10,
    firstName: "Sandra",
    lastName: "Nicouette",
    emailPlayer: "",
    Password: "fva-10-Nicouette",
    Man: false,
    joueur_interclubs: "loisir",
    joueur_capitaine: null,
    droits: "joueur",
    jour_ouverture: null,
    photos: "Sandra_Nicouette.jpg"
  },
  {
    id: 11,
    firstName: "Anne",
    lastName: "Abolisant",
    emailPlayer: "",
    Password: "fva-11-Abolisant",
    Man: false,
    joueur_interclubs: "equipe_1",
    joueur_capitaine: null,
    droits: "joueur",
    jour_ouverture: null,
    photos: "Anne_Abolisant.jpg"
  },
  {
    id: 12,
    firstName: "Elsa",
    lastName: "Rose",
    emailPlayer: "",
    Password: "fva-12-Rose",
    Man: false,
    joueur_interclubs: "equipe_2",
    joueur_capitaine: "capitaine_eq_2",
    droits: "capitaine",
    jour_ouverture: null,
    photos: "Elsa_Rose.jpg"
  },
  {
    id: 13,
    firstName: "Marc",
    lastName: "Assin",
    emailPlayer: "",
    Password: "fva-13-Assin",
    Man: true,
    joueur_interclubs: "equipe_1",
    joueur_capitaine: null,
    droits: "joueur",
    jour_ouverture: null,
    photos: "Marc_Assin.jpg"
  },
  {
    id: 14,
    firstName: "Oscar",
    lastName: "Ibou",
    emailPlayer: "",
    Password: "fva-14-Ibou",
    Man: true,
    joueur_interclubs: "loisir",
    joueur_capitaine: null,
    droits: "joueur",
    jour_ouverture: null,
    photos: "Oscar_Ibou.jpg"
  },
  {
    id: 15,
    firstName: "Abdel",
    lastName: "Icieux",
    emailPlayer: "",
    Password: "fva-15-Icieux",
    Man: true,
    joueur_interclubs: "loisir",
    joueur_capitaine: null,
    droits: "joueur",
    jour_ouverture: "mercredi",
    photos: "Abdel_Icieux.jpg"
  },
  {
    id: 16,
    firstName: "Cécile",
    lastName: "Anssieux",
    emailPlayer: "",
    Password: "fva-16-Anssieux",
    Man: false,
    joueur_interclubs: "equipe_1",
    joueur_capitaine: null,
    droits: "joueur",
    jour_ouverture: null,
    photos: "Cecile_Anssieux.jpg"
  },
  {
    id: 17,
    firstName: "Anne",
    lastName: "Ogastric",
    emailPlayer: "",
    Password: "fva-17-Ogastric",
    Man: false,
    joueur_interclubs: "equipe_2",
    joueur_capitaine: null,
    droits: "joueur",
    jour_ouverture: null,
    photos: "Anne_Ogastric.jpg"
  },
  {
    id: 18,
    firstName: "Franck",
    lastName: "Fort",
    emailPlayer: "",
    Password: "fva-18-Fort",
    Man: true,
    joueur_interclubs: "equipe_1",
    joueur_capitaine: null,
    droits: "joueur",
    jour_ouverture: null,
    photos: "Franck_Fort.jpg"
  },
  {
    id: 19,
    firstName: "Mehdi",
    lastName: "Khaman",
    emailPlayer: "",
    Password: "fva-19-Khaman",
    Man: true,
    joueur_interclubs: "equipe_2",
    joueur_capitaine: null,
    droits: "joueur",
    jour_ouverture: null,
    photos: "Mehdi_Khaman.jpg"
  },
  {
    id: 20,
    firstName: "Marthe",
    lastName: "Ini",
    emailPlayer: "",
    Password: "fva-20-Ini",
    Man: false,
    joueur_interclubs: "loisir",
    joueur_capitaine: null,
    droits: "joueur",
    jour_ouverture: "jeudi",
    photos: "Marthe_Ini.jpg"
  },
  {
    id: 21,
    firstName: "Jenny",
    lastName: "Fraireniseur",
    emailPlayer: "",
    Password: "fva-21-Fraireniseur",
    Man: false,
    joueur_interclubs: "loisir",
    joueur_capitaine: null,
    droits: "admin",
    jour_ouverture: null,
    photos: "Jenny_Fraireniseur.jpg"
  },
  {
    id: 22,
    firstName: "Sarah",
    lastName: "Joute",
    emailPlayer: "",
    Password: "fva-22-Joute",
    Man: false,
    joueur_interclubs: "equipe_1",
    joueur_capitaine: null,
    droits: "joueur",
    jour_ouverture: null,
    photos: "Sarah_Joute.jpg"
  },
  {
    id: 23,
    firstName: "Sandy",
    lastName: "Manché",
    emailPlayer: "",
    Password: "fva-23-Manche",
    Man: false,
    joueur_interclubs: "equipe_2",
    joueur_capitaine: null,
    droits: "joueur",
    jour_ouverture: null,
    photos: "Sandy_Manche.jpg"
  },
  {
    id: 24,
    firstName: "Marty",
    lastName: "Nais",
    emailPlayer: "",
    Password: "fva-24-Nais",
    Man: true,
    joueur_interclubs: "equipe_2",
    joueur_capitaine: null,
    droits: "joueur",
    jour_ouverture: null,
    photos: "Marty_Nais.jpg"
  },
  {
    id: 25,
    firstName: "Mouss",
    lastName: "Tache",
    emailPlayer: "",
    Password: "fva-25-Tache",
    Man: true,
    joueur_interclubs: "equipe_1",
    joueur_capitaine: null,
    droits: "joueur",
    jour_ouverture: null,
    photos: "Mouss_Tache.jpg"
  },
  {
    id: 26,
    firstName: "Callie",
    lastName: "Fornie",
    emailPlayer: "",
    Password: "fva-26-Fornie",
    Man: false,
    joueur_interclubs: "loisir",
    joueur_capitaine: null,
    droits: "joueur",
    jour_ouverture: "vendredi",
    photos: "Callie_Fornie.jpg"
  },
  {
    id: 27,
    firstName: "Jim",
    lastName: "Nastique",
    emailPlayer: "",
    Password: "fva-27-Nastique",
    Man: true,
    joueur_interclubs: "equipe_1",
    joueur_capitaine: null,
    droits: "joueur",
    jour_ouverture: null,
    photos: "Jim_Nastique.jpg"
  },
  {
    id: 28,
    firstName: "Laurent",
    lastName: "Bar",
    emailPlayer: "",
    Password: "fva-28-Bar",
    Man: true,
    joueur_interclubs: "equipe_2",
    joueur_capitaine: null,
    droits: "joueur",
    jour_ouverture: null,
    photos: "Laurent_Bar.jpg"
  },
  {
    id: 29,
    firstName: "Lara",
    lastName: "Clette",
    emailPlayer: "",
    Password: "fva-29-Clette",
    Man: false,
    joueur_interclubs: "equipe_1",
    joueur_capitaine: null,
    droits: "joueur",
    jour_ouverture: null,
    photos: "Lara_Clette.jpg"
  },
  {
    id: 30,
    firstName: "Emma",
    lastName: "Yonaise",
    emailPlayer: "",
    Password: "fva-30-Yonaise",
    Man: false,
    joueur_interclubs: "equipe_2",
    joueur_capitaine: null,
    droits: "joueur",
    jour_ouverture: null,
    photos: "Emma_Yonaise.jpg"
  }
]
module.exports = players